hmpps-auth:
  url: "http://localhost:8090/auth"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/em_data_insights
    username: hmpps
    password: hmpps

aws:
  region: eu-west-2
  athena:
    defaultDatabase: allied_mdss_dev
    mdssDatabase: allied_mdss_dev
    fmsDatabase: serco_fms_dev
    outputLocation: s3://emds-test-athena-query-results-20240923095933297100000013/output
    workgroup: 800964199911_default
    pollIntervalMs: 500
    timeoutMs: 60000
    role: ${ATHENA_GENERAL_IAM_ROLE:}