---
# Per environment values which override defaults in hmpps-electronic-monitoring-data-insights-api/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: "hmpps-em-emdi-maps-dev"

  ingress:
    host: electronic-monitoring-data-insights-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    ATHENA_OUTPUT_BUCKET: "s3://emds-test-athena-query-results-20240923095933297100000013"
    MFA_REQUIRED: "false"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_electronic_monitoring_data_insights_alerts_noprod
